import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "CoinAge",
  description:
    "Generated by create next appMonitor your cryptocurrency balance, track your portfolio, and manage your account effortlessly with our comprehensive crypto management platform. Stay updated with real-time data, detailed analytics, and personalized insights to make informed investment decisions.",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={inter.className}>{children}</body>
    </html>
  );
}
